import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Qr - Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>nattiana</h1>

        <div className={styles.grid}>
          <a href="/scan" className={styles.card}>
            <p>scan a wine label &rarr;</p>
          </a>
        </div>
      </main>
    </div>
  );
}
